@startuml
skinparam classAttributeIconSize 0
class Twitter {
  - users: Map<string, User>
  - tweets: Map<number, Tweet>
  + add_user(username: string): void
  + follow(follower: string, followed: string): void
  + tweet(username: string, text: string): Tweet
  + retweet(username: string, identifier: number, text: string): Tweet
  + remove_user(username: string): void
}
class User {
  + username: string
  - followers: Map<string, User>
  - following: Map<string, User>
  - timeline: Timeline
}
class Timeline {
  - tweets: Map<number, Tweet>
  + receive(tweet: Tweet): void
  + remove_author(username: string): void
}
class Tweet {
  + identifier: number
  + author: string
  + text: string
  + original: Tweet | null
  + likes: Set<string>
}
Twitter "1" *-- "0..*" User
Twitter "1" *-- "0..*" Tweet
User "0..*" -- "0..*" User : follows
User "1" *-- "1" Timeline
Timeline "1" o-- "0..*" Tweet
@enduml
