@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Car {
  + pass    : number
  + passMax : number
  + gas     : number
  + gasMax  : number
  + km      : number

  __
  
  + Car()
  + enter(): void
  + leave(): void
  + drive(value : number): void  
  + fuel (value : number): void
  + toString() : string
}

class Legenda {
  + atributoPublic
  - atributoPrivate
  # atributoProtected
  __
  + métodoPublic()
  - métodoPrivate()
  # métodoProtected()
}


@enduml