'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

'==
class Time {
  - hour   : int
  - minute : int
  - second : int
  __
  '
  ' inicializa os atributos todos para 0
  ' invoca os métodos setHour, setMinute e setSecond
  ' para tentar atribuir valores válidos
  + Time(hour : int, minute : int, second : int)
  '
  ' retorna string no formato hh:mm:ss
  + toString() : string
  __
  '
  ' apenas retorna o valor dos atributos
  + getHour()   : int
  + getMinute() : int
  + getSecond() : int
  __
  ' 
  ' se valor for válido, atribui ao atributo hour
  ' emite erro se for inválido
  + setHour  (value   : int)
  '
  ' se valor for válido, atribui ao atributo minute
  ' emite erro se for inválido
  + setMinute(value : int)
  '
  ' se valor for válido, atribui ao atributo second
  + setSecond(value : int)
  __
  '
  ' incrementa o atributo second em um segundo
  ' então, se necessário, incrementa o atributo minute
  ' e, se necessário, incrementa o atributo hour
  + nextSecond()
}
'--
@enduml