@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Shirt {
    - size: string
    __
    + constructor()
    + getSize(): string
    + setSize(size: string): boolean
}

@enduml
