@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Shirt {
    {static} + DEFAULT_SIZE: string
    - size: string
    __
    + constructor(size: string)
    + getSize(): string
    {static} + getAllowedSizes(): Array<string>
    + setSize(size: string): boolean
}

@enduml
