'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150
'==
class Car {
  + gas     : int
  + gasMax  : int
  + km      : int
  + pass    : int
  + passMax : int
  __
  '
  ' inicializar com tanque vazio
  ' 0 passageiros
  ' 0 de quilometragem
  + Car()
  '
  ' só embarca se o carro não estiver lotado
  ' embarca uma pessoa por vez
  + enter()
  '
  ' só desembar se houver alguém no carro
  ' desembarca uma pessoa por vez
  + leave()
  '
  ' só pode dirigir se houver algém no carro e algum combustível
  ' o carro faz 1km por litro
  + drive(km : int)
  '
  ' caso tente abastecer acima do limite, o valor em excesso deve ser descartado
  + fuel(gas : int)
  + toString() : string
}
'--
@enduml