'--
@startuml diagrama

skinparam defaultFontName Hasklig
skinparam dpi 150
'==
class Car {
  ' quantidade de passageiros no carro
  + pass    : int

  ' máximo de passageiros que o carro suporta
  + passMax : int

  ' gasolina atual do carro
  + gas     : int

  ' máximo de gasolina que o carro suporta
  + gasMax  : int

  ' quilometragem atual do carro
  + km      : int

  __
  
  ' inicializar todos os atributos
  ' inicializar com tanque vazio
  ' 0 passageiros
  ' 0 de quilometragem
  ' máximo de 2 pessoas
  ' máximo de 100 litros de gasolina
  + Car()

  ' embarca uma pessoa no carro
  ' verifique se o carro não estiver lotado
  + enter()
  
  ' desembarca uma pessoa por vez
  ' verifique se tem alguém no carro
  + leave()
  
  ' percorre value quilometros com o carro
  ' gasta um litro de gas para cada km de distancia
  ' verifique se tem alguém no carro
  ' verifique se tem gasolina suficiente

  + drive(value : int): void
  
  ' incrementa gasolina no tanque de value
  ' caso tente abastecer acima do limite de gasMax
  '   o valor em excesso deve ser descartado
  
  + fuel(value : int)

  + toString() : string
}
'--
@enduml