@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

left to right direction 

Person "0..1" <--o "1" Motorcycle : Carry

class Person {
  - age : int
  - name : String
  + Person(name : String, age : int)
  __
  + getAge() : int
  + getName() : String
  --
  + toString() : String
}

class Motorcycle {
  - person : Person
  - power : int
  - time : int
  __
  + Motorcycle(power : int)
  + buy(time : int)
  + drive(time : int)
  + enter(person : Person) : boolean
  + honk()
  + leave() : Person
  __
  + getPerson() : Person
  + getPower() : int
  + getTime() : int
  --
  + toString() : String
}

@enduml