@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Animal {
    + species: string
    + noise  : string
    + age    : number
    __
    + constructor(species: string, noise: string)
    + makeSound(): string
    + ageBy(increment: number): boolean
    + toString(): string
}

@enduml
