@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

package com.qxcode {
  class Lead {
    - hardness  : string
    - size      : int
    - thickness : float
    __
    + Lead(thickness : float, hardness : string, size : int)
    + usagePerSheet() : int
    + toString() : string
    __
    + getHardness()  : string
    + getSize()      : int
    + getThickness() : float
    + setSize(size : int)
  }
  class Pencil {
    - thickness : float
    - tip : Lead | null
    __
    + Pencil(thickness : float)
    + hasGrafite()        : boolean
    + insert(lead : Lead) : boolean
    + remove()            : Lead | null
    + writePage()
    + toString() : string
    __
    + getThickness() : float
  }
}
Pencil "1" --> "0..1" Lead
@enduml