'--
@startuml
skinparam defaultFontName Hasklig
skinparam dpi 150
left to right direction

'==
class Lead {
  - thickness : float
  - hardness  : string
  - size      : int
  __
  '
  ' inicializa os atributos do grafite
  + Lead(thickness : float, hardness : string, size : int)
  '
  ' retorna o gasto em milímetros para uma página escrita
  ' 1mm para HB
  ' 2mm para 2B
  ' 4mm para 4B
  ' 6mm para 6B
  + usagePerSheet() : int
  __
  + setSize(size : int)
  __
  + getHardness()      : string
  + getSize()          : int
  + getThickness()     : float
}

class Pencil {
  - thickness : float
  - tip : Lead | null
  __
  '
  ' inicializa os atributos da lapiseira
  ' lembre de inicializar tip como null
  + Pencil(thickness : float)
  '
  ' retorna true se tem grafite na lapiseira
  + hasGrafite()        : boolean
  '
  ' verifica se ja tem grafite
  ' verifica se o grafite tem espessura compatível
  ' insere o grafite na lapiseira
  + insert(lead : Lead) : boolean
  '
  ' se houver grafite, remove e retorna o grafite
  ' se nao houver grafite, retorna null
  + remove()            : Lead | null
  '
  ' verifica se tem grafite
  ' verifica se tem mais de 10mm
  ' se tiver menos que o necessário para página, escreve parcialmente
  ' se tiver mais que o necessário para página, escreve totalmente
  + writePage()         : void
  '
  + toString()          : string
  __
  + getThickness()      : float
}
'--

Pencil "1" --> "0..1" Lead
@enduml