@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150
left to right direction

package com.qxcode {
  enum Hardness {
    HB
    2B
    4B
    6B
  }
  
  class Lead {
    - thickness : float
    - hardness  : Hardness
    - size      : int
    - usagePerSheet: int
    __
    + Lead(thickness : float, hardness : Hardness, size : int)
    + toString() : string
    __
    + setSize(size : int)
    __
    + getHardness()      : Hardness
    + getSize()          : int
    + getThickness()     : float
    + getUsagePerSheet() : int
  }

  class Pencil {
    - thickness : float
    - tip : Lead | null
    __
    + Pencil(thickness : float)
    + hasGrafite()        : boolean
    + insert(lead : Lead) : boolean
    + remove()            : Lead | null
    + writePage()         : void
    + toString()          : string
    __
    + getThickness()      : float
  }
}
Pencil "1" --> "0..1" Lead
Lead -- Hardness
@enduml