
@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction
class Player {
  - label: number  
  - pos  : number
  - trapped : boolean
  __
  + Player(label: number)
  + isTrapped()   : boolean
  + toString() : string
  __
  + getLabel(): number
  + getPos()  : number
  + setPos(pos: number): void
  + setTrapped(trapped : boolean): void
}

enum EventType {
  MOVED
  TRAPPED
  RELEASED
  STAYED_TRAPPED
  WON
}

class RoundEvent {
  + eventType: EventType
  + playerLabel: number
  + position: number
}

class Board {
  - trapList : Array<number>
  - players  : Array<Player>
  - running  : boolean
  - boardSize: number
  __
  + Board(nPlayers: number, boardSize: number)
  + toString(): string
  __
  + addTrap (pos  : number): void
  + rollDice(value: number): Array<RoundEvent>
}

Board "1" *--  "2..*" Player : > has
@enduml
