
@startuml
skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

enum InsertResult {
    OK
    WRONG_THICKNESS
}

enum PullResult {
    OK
    TIP_OCCUPIED
    BARREL_EMPTY
}

enum WriteResult {
    OK
    NO_LEAD
    INSUFFICIENT
    INCOMPLETE
}

' Grafite
class Lead {
    - hardness  : string
    - thickness : number
    - size      : number
    __
    + Lead(thickness: number, hardness: string, size: number)
    __
    + getWearPerPage(): number
    + getSize()      : number
    + getThickness() : number
    + getHardness()  : string
    + consume(amount: number): boolean
    + toString(): string
}

class Pencil {
    - thickness: number
    - tip      : Lead | null
    - barrel   : Array<Lead>
    __
    + Pencil(thickness : number)
    __
    + insert(lead: Lead) : InsertResult
    + remove()   : Lead | null
    + pull()     : PullResult
    + writePage(): WriteResult
    __
    + toString() : string
}

Pencil "1" o--  "0..*" Lead : > Stores
@enduml
