@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Animal {
    + species: string
    + sound  : string
    + age    : number
    __
    + constructor(species: string, sound: string)
    + makeSound(): string
    + ageBy(increment: number): void
    + toString(): string
}

class Legend {
  + publicAttribute
  - privateAttribute
  # protectedAttribute
  __
  + publicMethod()
  - privateMethod()
  # protectedMethod()
}

@enduml
