@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Person {
  - name : string
  __
  + Person(name : string)
  + toString() : string
  __
  + getName() : string
  + setName(name : string): void
}

enum CallResult {
  OK
  INVALID_COUNTER
  BUSY_COUNTER
  EMPTY_WAITING
}

enum FinishResult {
  OK
  INVALID_COUNTER
  EMPTY_COUNTER
}

class Market {
  - counters : Array<Person | null>
  - waiting  : Array<Person>
  __
  - validateIndex(index: number): boolean
  __
  + Market(counterCount: number)
  + toString(): string
  __
  + arrive (person: Person): void
  + call   (index : number): CallResult
  + finish (index : number): Person | null
  + cutInLine(sneaky: Person, fool: string): boolean
  + giveUp (quitter: string): Person | null
}

Market "1" o-- "0..*" Person
@enduml
