
@startuml
skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

' Grafite
class Lead {
    - hardness  : string
    - thickness : number
    - size      : number
    __
    + Lead(thickness: number, hardness: string, size: number)
    __
    + usagePerSheet(): number
    + getSize()      : number
    + getThickness() : number
    + getHardness()  : string
    __
    + setSize(size : number)
    __
    + toString(): string
}

class Pencil {
    - thickness: number
    - tip      : Lead | null
    - barrel   : Array<Lead>
    __
    + Pencil(thickness : number)
    __
    + insert(lead: Lead) : boolean
    + remove()   : Lead | null
    + pull()     : boolean
    + writePage(): void
    __
    + toString() : string
}

Pencil "1" o--  "0..*" Lead : > Stores
@enduml