@startuml
class WhatsApp {
  - users: Map<string, User>
  - groups: Map<number, Group>
  + create(owner: string, name: string): Group
  + invite(owner: string, invitee: string, id: number): void
  + send(user: string, id: number, text: string): void
  + read(user: string, id: number): string
}
class User {
  + username: string
  - groups: Map<number, Group>
}
class Group {
  + identifier: number
  + name: string
  - members: Map<string, User>
  - unread: Map<string, Array<Message>>
}
class Message
WhatsApp "1" *-- "0..*" User
WhatsApp "1" *-- "0..*" Group
Group "0..*" o-- "0..*" User
Group "1" o-- "0..*" Message
@enduml
