
@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Pessoa {
  - nome : string
  __
  + Pessoa(nome : string)
  + toString()  : string
  __
  + getNome()    : string
  + setNome(nome : string): void
}

class Mercantil {
  - caixas : Array<Pessoa | null>
  - espera : List <Pessoa>
  __
  - validarIndice(indice: int): boolean
  __
  + Mercantil(qtdCaixas: int)
  + toString(): string
  __
  + chegar   (pessoa : Pessoa): void
  + chamar   (indice : int)   : boolean
  + finalizar(indice : int)   : Pessoa | null
  + furarFila(furao: Pessoa, besta: string): boolean
  + desistir (desistente: string): boolean
}

Pessoa "0..*" --o  "1" Mercantil
@enduml