@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Coin {
  - value: number
  - volume: number
  - label: string
  __
  + Coin(value: number, volume: number, label: string)
  + toString(): string
}

class Item {
  - label: string
  - volume: number
  __
  + Item(label: string, volume: number)
  + toString(): string
}

class Pig {
  - maxVolume: number
  - coins: Array<Coin>
  - items: Array<Item>
  - broken: boolean
  __
  + Pig(maxVolume: number)
  + addCoin(coin: Coin): void
  + addItem(item: Item): void
  + breakPig(): void
  + extractCoins(): Array<Coin>
  + extractItems(): Array<Item>
  + value(): number
  + volume(): number
  + toString(): string
}

Pig "1" *-- "0..*" Coin
Pig "1" *-- "0..*" Item

@enduml
