@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

Organizacao "contratante" -- "contratado" Empregado : contrata

class Organizacao {
  - contratados : Empregado[0..*]
}

@enduml