@startuml

left to right direction

class AssociacaoEsportiva {
    +nome: String
    +adicionarEquipe(equipe: Equipe): void
}

class Equipe {
    +nome: String
    +adicionarJogador(jogador: Jogador): void
}

class Jogador {
    +nome: String
}

AssociacaoEsportiva o-- "0..*" Equipe
Equipe "1" o-- "0..*" Jogador
Jogador "0..*" -- "0..*" Equipe
@enduml
