@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Motorcycle {
  - person: Person | null
  - power : number
  - time  : number
  __
  + constructor(power: number)
  + enter(person: Person): boolean
  + leave(): Person | null
  __
  + buy(time : number): void
  + drive(time : number): string | null
  + honk()                : string
  __
  + getPerson(): Person | null
  + getPower() : number
  + getTime()  : number
  __
  + toString(): string
}
  
class Person {
  - age : number
  - name: string
  __
  + constructor(name: string, age: number)
  __
  + getAge() : number
  + getName(): string
  __
  + toString(): string
}

Motorcycle "1" o-- "0..1" Person : agrega

note right of Motorcycle
  A moto pode não ter uma pessoa agregada.
  A multiplicidade 0..1 representa essa ausência.
  leave() e getPerson() podem não retornar uma pessoa.
end note
@enduml
