@startuml
skinparam classAttributeIconSize 0

abstract class Account {
  # identifier: number
  # client_id: string
  # balance: number
  + deposit(value: number): void
  + withdraw(value: number): void
  + transfer_to(other: Account, value: number): void
  + monthly_update(): void
}
class CheckingAccount
class SavingsAccount
class Client {
  - identifier: string
  - accounts: Array<Account>
  + add_account(account: Account): void
}
class BankAgency {
  - clients: Map<string, Client>
  - accounts: Map<number, Account>
  + add_client(client_id: string): void
  + deposit(identifier: number, value: number): void
  + withdraw(identifier: number, value: number): void
  + transfer(source: number, target: number, value: number): void
  + monthly_update(): void
}
Account <|-- CheckingAccount
Account <|-- SavingsAccount
Client "1" o-- "0..*" Account
BankAgency "1" *-- "0..*" Account
BankAgency "1" *-- "0..*" Client
@enduml
