@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

enum Result {
  OK
  CAR_EMPTY
  NO_GAS
  INCOMPLETE
}

class Car {
  + pass    : number
  + passMax : number
  + gas     : number
  + gasMax  : number
  + km      : number
  __
  + constructor()
  + enter() : boolean
  + leave() : boolean
  + drive(distance : number) : Result
  + fuel(increment : number) : void
  + toString() : string
}

class Shell {
  __
  + main(args : Array<string>) : void
}

Shell ..> Car : usa
Shell ..> Result : interpreta

@enduml
