@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

enum DriveResult {
  OK
  NO_PASSENGERS
  NO_GAS
  INCOMPLETE
}

class Car {
  + pass    : number
  + passMax : number
  + gas     : number
  + gasMax  : number
  + km      : number
  __
  + constructor()
  + enter() : boolean
  + leave() : boolean
  + drive(distance : number) : DriveResult
  + fuel(increment : number) : void
  + toString() : string
}

class Shell {
  __
  + main() : void
}

Shell ..> Car : usa
Shell ..> DriveResult : interpreta

@enduml
