@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Pet {
  - id: number
  - name: string
  - species: string
  __
  + Pet(id: number, name: string, species: string)
  + toString(): string
}

class Client {
  - id: string
  - name: string
  - pets: Map<string, Pet>
  __
  + Client(id: string, name: string)
  + addPet(pet: Pet): void
  + getPet(name: string): Pet
  + toString(): string
}

class Service {
  - id: string
  - price: number
  __
  + Service(id: string, price: number)
  + toString(): string
}

class Sale {
  - id: number
  - clientId: string
  - petName: string
  - serviceId: string
  - price: number
  __
  + Sale(id: number, clientId: string, petName: string, serviceId: string, price: number)
  + toString(): string
}

class Clinic {
  - clients: Map<string, Client>
  - services: Map<string, Service>
  - sales: Array<Sale>
  - nextPetId: number
  - nextSaleId: number
  __
  + addClient(id: string, name: string): void
  + getClient(id: string): Client
  + deleteClient(id: string): void
  + addPet(clientId: string, name: string, species: string): void
  + addService(id: string, price: number): void
  + sell(clientId: string, petName: string, serviceId: string): void
  + balance(): number
}

Client "1" *-- "0..*" Pet
Clinic "1" *-- "0..*" Client
Clinic "1" *-- "0..*" Service
Clinic "1" *-- "0..*" Sale

@enduml
