@startuml

' Configurações visuais
skinparam classAttributeIconSize 0
skinparam linetype ortho

' 1. Classe Abstrata
abstract class Pagamento {
    + valor : float
    + descricao : str
    __
    + resumo() : void
    + validar_valor() : void
    + {abstract} processar() : void
}

' 2. Subclasses Concretas
class CartaoCredito {
    + numero : str
    + nome_titular : str
    + limite_disponivel : float
    __
    + processar() : void
}

class Pix {
    + chave : str
    + banco : str
    __
    + processar() : void
}

class Boleto {
    + codigo_barras : str
    + vencimento : str
    __
    + processar() : void
}

' 3. Representação do Script/Função Global
class "Client / Main" as Main << Script >> {
    + pagamentos : List<Pagamento>
    __
    + processar_pagamento(p: Pagamento) : void
}

' Relacionamentos
Pagamento <|-- CartaoCredito
Pagamento <|-- Pix
Pagamento <|-- Boleto

' A função global depende da abstração Pagamento para funcionar
Main ..> Pagamento : <<usa>>

note right of Pagamento::processar
  Método abstrato:
  Força as subclasses a
  implementarem a lógica.
end note

note right of Main::processar_pagamento
  Recebe qualquer objeto
  que herde de Pagamento
  (Polimorfismo)
end note

@enduml