@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

abstract class PaymentMethod {
  + {abstract} process(amount: number): string
}

class CreditCard {
  + holder: string
  + limit: number
  + process(amount: number): string
}

class Pix {
  + key: string
  + bank: string
  + process(amount: number): string
}

class Boleto {
  + barcode: string
  + dueDate: string
  + process(amount: number): string
}

class Payment {
  + amount: number
  + description: string
  - method: PaymentMethod
  + process(): string
}

class processPayments {
  + processPayments(payments: Array<Payment>): Array<string>
}

PaymentMethod <|.. CreditCard
PaymentMethod <|.. Pix
PaymentMethod <|.. Boleto
Payment "1" *-- "1" PaymentMethod
processPayments ..> Payment

@enduml
