@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

enum Label {
  GIVE
  TAKE
  PLUS
}

class Operation {
  - id: number
  - name: string
  - label: Label
  - value: number
  __
  + Operation(id: number, name: string, label: Label, value: number)
  + toString(): string
}

class Client {
  - name: string
  - limit: number
  - operations: Array<Operation>
  __
  + Client(name: string, limit: number)
  + addOperation(operation: Operation): void
  + balance(): number
  + toString(): string
}

class Agiota {
  - clients: Map<string, Client>
  - deadClients: Array<Client>
  - operations: Array<Operation>
  - deadOperations: Array<Operation>
  - nextOperationId: number
  __
  - client(name: string): Client
  - addOperation(client: Client, label: Label, value: number): void
  __
  + addClient(name: string, limit: number): void
  + give(name: string, value: number): void
  + take(name: string, value: number): void
  + kill(name: string): void
  + plus(): void
  + clientText(name: string): string
  + toString(): string
}

Client "1" o-- "0..*" Operation
Agiota "1" *-- "0..*" Operation
Agiota "1" *-- "0..*" Client

@enduml
