@startuml
skinparam classAttributeIconSize 0

class Phone {
  + label: string
  + number: string
  + is_valid(): boolean
  + toString(): string
}

class Contact {
  - name: string
  - favorite: boolean
  - phones: Array<Phone>
  + name: string {readOnly}
  + favorite: boolean {readOnly}
  + Contact(name: string)
  + add_phone(label: string, number: string): boolean
  + remove_phone(index: number): boolean
  + toggle_favorite(): void
  + toString(): string
}

Contact "1" *-- "0..*" Phone : phones
@enduml
