@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Person {
  - name : string
  __
  + Person(name : string)
  + toString() : string
  __
  + getName() : string
  + setName(name : string): void
}

class Market {
  - counters : Array <Person | null>
  - waiting  : Array <Person>
  __
  - validateIndex(index: number): boolean
  __
  + Market(counterCount: number)
  + toString(): string
  __
  + arrive (person: Person): void
  + call   (index : number): boolean
  + finish (index : number): Person | null
  + cutInLine(sneaky: Person, fool: string): boolean
  + giveUp (quitter: string): Person | null
}

Person "0..*" --o "1" Market
@enduml
