@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Slipper {
    {static} + MIN_SIZE: number
    {static} + MAX_SIZE: number
    - size: number
    __
    + constructor()
    + getSize(): number
    + setSize(size: number): boolean
}

@enduml
