'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

'==
class Contact {
  # prefix : String
  - fones : List<Fone>
  - name : String
  __
  
  ' crie um ArrayList para o ATRIBUTO fones
  ' se a variável fones não for null, adicione todos os fones usando o método addFone
  + Contact(name : String, fones : List<Fone>)
  
  ' se fone for válido, insira no atributo fones
  ' se não, informe o erro
  + addFone(fone : Fone)
  
  ' se o índice existir no ArrayList, remova o telefone com esse índice
  + rmFone(index : int)
  
  ' use um contador para mostrar o índice do telefone
  ' use o toString do fone para adicioná-lo à saída
  ' o resultado dever ficar assim:
  ' ex: - david [0:oi:123] [1:tim:9081] [2:claro:5431]
  + toString() : String
  __
  + getFones() : List<Fone>
  + getName() : String
  
  ' limpe a lista de fones
  ' utilize o addFone para adicionar apenas os fones válidos
  + setFones(fones : List<Fone>)
  + setName(name : String)
}

class Fone {
  - id : String
  - number : String
  __
  + Fone(id : String, number : String)
  
  ' utiliza o static validate para retornar se essa instancia do fone é valida
  + isValid() : boolean
  
  ' verifica se o número é um número de telefone válido
  + validate(number : String) : boolean {static}
  
  ' o resultado deve ficar assim
  ' ex: oi:1234
  + toString() : String
  __
  
  + getId() : String
  + getNumber() : String
  + setId(id : String)
  + setNumber(number : String)
}
'--
Contact -->  "-fones" Fone
@enduml
