
@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Animal {
    + especie: string
    + barulho: string
    + idade  : number
    __
    + Animal(especie: string, barulho: string)
    + fazerBarulho(): string
    + envelhecer(qtd: number): void
    + toString(): string
}

class Legenda {
  + atributoPublic
  - atributoPrivate
  # atributoProtected
  __
  + métodoPublic()
  - métodoPrivate()
  # métodoProtected()
}


@enduml
