@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

enum Result {
  OK
  NO_BATTERY
  DIVISION_BY_ZERO
}

class Calculator {
  + battery    : number
  + batteryMax : number
  + display    : number
  __
  + constructor(batteryMax : number)
  + charge(increment : number) : void
  + sum(a : number, b : number) : Result
  + division(num : number, den : number) : Result
  + toString() : string
}

class Shell {
  __
  + printResult(result : Result) : void
}

Shell ..> Calculator : usa
Shell ..> Result : interpreta

@enduml