'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

'==
class Account {
  - balanceManager : BalanceManager
  - id : int
  __
  + Account(id : int)

  ' adiciona valor à conta
  + deposit(label : Label, value : int) : boolean

  ' retira o dinheiro, mesmo que o balance fique negativo
  + fee(value : int) : boolean

  ' se o índice for válido e representar uma operação de fee
  ' adicione o mesmo valor tarifado, mas com label de reverse
  + reverse(index : int) : boolean

  ' só realiza a operação se houver dinheiro suficiente na conta
  + withdraw(value : int) : boolean
  + toString() : String
  __
  + getBalanceManager() : BalanceManager
}
'
' nessa classe são efetivadas e registradas as alterações no saldo
class BalanceManager {
  - balance : int
  - extract : List<Operation>
  - nextId : int
  __
  + BalanceManager()

  ' adiciona value ao balance
  ' crie operação e adiciona ao vetor de operações
  ' incrementa o nextId
  + addOperation(label : Label, value : int)
  + toString() : String
  __
  + getBalance() : int

  ' metodo sobrescrito para retornar apenas as últimas qtdOp operações
  + getExtract() : List<Operation>
  + getExtract(qtdOp : int) : List<Operation>
}
'
' essa enumeração guarda possíveis labels para as operações
enum Label {
  + deposit {static}
  + fee {static}
  + opening {static}
  + reverse {static}
  + withdraw {static}
  - name : String
  __
  + valueOf(name : String) : Label {static}
  + values() : Label[] {static}
  + toString() : String
  __
  + getName() : String
}
'
' operação guarda os dados de uma única operação
class Operation {
  - balance : int
  - index : int
  - label : Label

  ' valor em negativo se for débito
  - value : int
  __
  + Operation(index : int, label : Label, value : int, balance : int)

  ' faz o preenchimento da string com espaços em branco até completar o length
  + pad(string : String, length : int) : String {static}
  + toString() : String
  __
  + getBalance() : int
  + getIndex() : int
  + getLabel() : Label
  + getValue() : int
}

'--
Account "1" -->  "1" BalanceManager
BalanceManager "1" -->  "0..*" Operation
Operation "1" -->  "1" Label
@enduml