@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Calculator {

  + battery    : number
  + batteryMax : number
  + display    : number
  __

  + constructor(batteryMax : number)
  + charge(increment : number): void
  + sum(a : number, b : number): void
  + division(num : number, den : number): void
  + toString(): string
}

class Legenda {
  + atributePublic
  - atributePrivate
  # atributeProtected
  __
  + methodPublic()
  - methodPrivate()
  # methodProtected()
}

@enduml
