@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

left to right direction

Ator "1..*" -- "1..*" Filme
(Ator, Filme) .. Atua

class Ator {
  - nomeAtor : String
}

class Filme {
  - tituloFilme : String
  - genero : Time
}

class Atua {
  - papelAtor : String
}

@enduml