@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

left to right direction 

Lapiseira "1" o-- "0..*" Grafite : usa

class Lapiseira {
  - calibre : float
  - ponta : Grafite | null
  - barril: Array<Lead>
  __
  + inserir(grafite : Grafite) : boolean
  + remover() : Grafite | null
}

class Grafite {
  - calibre : float
  - dureza  : String
  - tamanho : float
}

@enduml