@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

left to right direction

class Pet {
    - energyMax: int
    - hungryMax: int
    - cleanMax: int
    - energy: int
    - hungry: int
    - clean: int
    - diamonds: int
    - age: int
    - alive: boolean
    __
    + Pet(energy: int, hungry: int, clean: int)
    + isAlive(): boolean
    + toString(): String
    __
    + setEnergy(value: int): void
    + setHungry(value: int): void
    + setClean(value: int): void
    + setDiamonds(value: int): void
    + setAge(value: int): void
    + getClean(): int
    + getHungry(): int
    + getEnergy(): int
    + getCleanMax(): int
    + getHungryMax(): int
    + getEnergyMax(): int
    + getDiamonds(): int
    + getAge(): int
}

class Game {
    - pet: Pet
    __
    + Game(pet: Pet)
    - testAlive(): boolean
    + toString(): String
    __
    + play(): void
    + shower(): void
    + eat(): void
    + sleep(): void
}

Game "1" *-- "1" Pet

@enduml
