@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

left to right direction

class Pet {
    - energyMax: number
    - hungryMax: number
    - cleanMax : number
    - energy   : number
    - hungry   : number
    - clean    : number
    - diamonds : number
    - age      : number
    - alive    : boolean
    __
    + Pet(energy: number, hungry: number, clean: number)
    + isAlive(): boolean
    + toString(): string
    __
    + setEnergy(value: number)  : void
    + setHungry(value: number)  : void
    + setClean(value: number)   : void
    + setDiamonds(value: number): void
    + setAge(value: number)     : void
    __
    + getClean()    : number
    + getHungry()   : number
    + getEnergy()   : number
    + getCleanMax() : number
    + getHungryMax(): number
    + getEnergyMax(): number
    + getDiamonds() : number
    + getAge()      : number
}

class Game {
    - pet: Pet
    __
    + Game(pet: Pet)
    - testAlive(): boolean
    + toString() : string
    __
    + play()  : void
    + shower(): void
    + eat()   : void
    + sleep() : void
}

Game "1" *-- "1" Pet

@enduml
