
@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150


class Slot {
    - name : string
    - price : number
    - quantity : number
    __
    + Slot(name : string, price: number, quantity: number)
    __
    + getName() : string
    + getPrice() : number
    + getQuantity() : number
    + setName(name: string) : void
    + setPrice(price: number) : void
    + setQuantity(quantity: number) : void
    __
    + toString() : string
}

class VendingMachine {
    - slots : Array<Slot>
    - profit : number
    - cash   : number
    - capacity : number
    __

    ' inicialize a máquina criando todos os slots
    + VendingMachine(capacity: number)
    __

    ' se houver slot nessa posição, retorne
    ' se não, retorne null ou lance uma exceção
    + getSlot(index: number) : Slot

    ' altere o valor slot nessa posição
    + setSlot(index: number, slot: Slot) : void

    ' limpe as informações do slot nessa posição
    + clearSlot(index: number) : void
    __

    ' adicione dinheiro no cash da máquina
    + insertCash(cash: number) : void

    ' retorne o valor do cash da máquina e zere o cash
    + withdrawCash() : number

    ' informe o valor do cash sem zerar o cash
    + getCash() : number

    ' informe o valor apurado com todas as vendas
    + getProfit() : number
    __

    ' se existir produto nessa posição
    ' se o dinheiro do cash for suficiente
    ' se a quantidade do produto for maior que zero
    ' deduza da quantidade 1
    ' deduza do cash o valor do produto
    + buyItem(index: number) : void
    --
    + toString() : string
}

VendingMachine "1" o-- "1..*" Slot
@enduml
