'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150
'==
class Motorcycle {
  - person : Person | null
  - power  : int
  - time   : int
  __
  
  ' a moto inicia com 1 de potência, sem minutos e sem ninguém
  + Motorcycle(power : int)
  '
  ' só pode estar uma pessoa na moto por vez
  ' para subir, informe nome e idade de quem está subindo
  + insertPerson(person : Person) : boolean
  
  ' só pode descer se estiver alguém na moto
  + remove() : Person | null
  + buyTime(time : int)
  
  ' só pessoas de 10 anos ou menos podem passear na moto
  ' uma pessoa só pode passear na moto se a moto estiver tempo
  ' se o tempo acabar no meio do passeio, informe o quanto a pessoa andou
  + drive(time : int)
  
  ' qualquer pessoa pode buzinar a moto
  ' o barulho da buzina é "Pem"
  ' o "e" deve ser repetido power vezes
  + honk()
  __
  + getPerson() : Person
  + getPower()  : int
  + getTime()   : int
  __
  
  ' retorna o tempo, potencia e o nome da pessoa
  ' ex: power:5, time:0, person:(marcos:4)
  + toString()  : string
}
  
class Person {
  - age  : int
  - name : string
  __
  + Person(name : string, age : int)
  __
  + getAge()  : int
  + getName() : string
  __
  
  ' retorna o nome e a idade da pessoa
  ' nome:idade
  + toString() : string
}
'--
Person "0..1" --o "1" Motorcycle : < Carry
@enduml
