@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

enum DivisionResult {
  OK
  NO_BATTERY
  DIVISION_BY_ZERO
}

class Calculator {
  + battery    : number
  + batteryMax : number
  + display    : number
  __
  + constructor(batteryMax : number)
  + chargeBattery(increment : number) : void
  + sum(a : number, b : number) : boolean
  + division(num : number, den : number) : DivisionResult
  + toString() : string
}

class Shell {
  __
  + printSumResult(success : boolean) : void
  + printDivisionResult(result : DivisionResult) : void
}

Shell ..> Calculator : usa
Shell ..> DivisionResult : interpreta

@enduml
