'--
@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150
'==
  class Player {
    - label: int  
    - pos  : int
    - free : boolean
    __
    + Player(label: int)
    + isFree()   : boolean
    + toString() : string
    __
    + getLabel() : int
    + getPos()   : int
    + setPos(pos : int)
    + setFree(free : boolean)
  }

  class Board {
    - trapList  : Array<int>
    - players   : Array<Player>
    - running   : boolean
    - boardSize : int
    __
    + Board(nPlayers : int, boardSize : int)
    + toString() : string
    __
    + addTrap(pos : int)
    + rollDice(value : int)
  }
'--
Board "1" *--  "2..*" Player : > has
@enduml
