@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

left to right direction 

Pessoa -- Livro : escreve

class Pessoa {
  - nome : String
}

class Livro {
  - autor : Pessoa
}

@enduml