@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

package com.qxcode {
  class Client {
    - fone : string
    - id   : string
    __
    + Client(id : string, fone : string)
    __
    + getFone() : string
    + getId()   : string
    + setFone(fone : string)
    + setId(id : string)
    __
    + toString() : string
  }
  class Sala {
    - cadeiras : Array<Client | null>
    __
    + Sala(capacidade : int)
    + cancelar(id : string)
    + reservar(id : string, fone : string, ind : int) : boolean
    __
    + getCadeiras() : Array<Client | null>
    __
    + toString() : string
  }
}
Sala "1" o-- "0..*" Client
@enduml