@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150


class Time {
  - hour  : number
  - minute: number
  - second: number
  __
  
  + Time(hour: number, minute: number, second: number)
  __
  + getHour()  : number
  + getMinute(): number
  + getSecond(): number
  __
  + setHour  (value: number): void
  + setMinute(value: number): void
  + setSecond(value: number): void
  __
  + nextSecond()             : void
}

class Legenda {
  + atributoPublic
  - atributoPrivate
  # atributoProtected
  __
  + métodoPublic()
  - métodoPrivate()
  # métodoProtected()
}

@enduml