@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150


class Time {
  - hour  : number
  - minute: number
  - second: number
  __
  
  + constructor(hour: number, minute: number, second: number)
  __
  + getHour()  : number
  + getMinute(): number
  + getSecond(): number
  __
  + setHour  (value: number): boolean
  + setMinute(value: number): boolean
  + setSecond(value: number): boolean
  __
  + nextSecond()             : void
  + toString()               : string
}

class Shell {
  + main(): void
}

Shell ..> Time : usa

@enduml
