@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150


class Time {
  {static} + MIN_VALUE: number
  {static} + MAX_HOUR: number
  {static} + MAX_MINUTE: number
  - hour  : number
  - minute: number
  - isAmPm: boolean
  __
  
  + constructor(hour: number, minute: number)
  __
  + getHour()  : number
  + getMinute(): number
  + isAmPm()    : boolean
  __
  + setHour  (value: number): boolean
  + setMinute(value: number): boolean
  __
  + nextMinute()             : void
  + toggleMode()             : void
  + toString()               : string
}

class Shell {
  + main(): void
}

Shell ..> Time : usa

@enduml
