@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

left to right direction

Pessoa "1..*" o-- "1..*" ContaComum : possui

class Pessoa {
  - nome : String
  - endereco : String
  - cep : long
  - telefone : String
  - renda : double
  - conta : ContaComum[1..*]
}

class ContaComum {
  - numero : long
  - aberturaConta : Data
  - fechamentoConta : Date[0..1]
  - saldo : double
}

@enduml