@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

interface Shape {
  + name(): string
  + area(): number
  + perimeter(): number
}

class Point2D {
  + x: number
  + y: number
  + toString(): string
}

class Circle {
  - center: Point2D
  - radius: number
  + name(): string
  + area(): number
  + perimeter(): number
  + toString(): string
}

class Rectangle {
  - p1: Point2D
  - p2: Point2D
  + name(): string
  + area(): number
  + perimeter(): number
  + toString(): string
}

class Shell {
  + main(): void
}

Circle ..|> Shape
Rectangle ..|> Shape
Circle "1" *-- "1" Point2D
Rectangle "1" *-- "2" Point2D
Shell ..> Shape : usa

@enduml
