@startuml
skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

enum InsertResult {
    OK
    ALREADY_HAS_LEAD
    WRONG_THICKNESS
}

enum WriteResult {
    OK
    NO_LEAD
    INSUFFICIENT
    INCOMPLETE
}

class Lead {
    {static} + MIN_SIZE: number
    - thickness: number
    - hardness : string
    - size     : number
    __
    + constructor(thickness: number, hardness: string, size: number)
    + getWearPerPage(): number
    + consume(amount: number): boolean
    __
    + getHardness() : string
    + getSize()     : number
    + getThickness(): number
    + toString(): string
}

class Pencil {
    
    - thickness: number
    - tip      : Lead | null
    __

    + constructor(thickness : number)
    + hasLead()          : boolean
    + insert(lead : Lead): InsertResult
    + remove()           : Lead | null
    + writePage()        : WriteResult
    __
    + toString()         : string
}

Pencil "1" o-- "0..1" Lead : agrega

note right of Pencil
  Uma lapiseira pode não ter grafite agregado.
  A multiplicidade 0..1 representa essa ausência.
  remove() pode não retornar um grafite.
end note
@enduml
