@startuml
skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Lead {
    - thickness: number
    - hardness : string
    - size     : number
    __
    + Lead(thickness: number, hardness: string, size: number)
    + usagePerSheet(): number
    __
    + getHardness() : string
    + getSize()     : number
    + getThickness(): number
    __
    + setSize(size: number): void
    __
    + toString(): string
}

class Pencil {
    
    - thickness: number
    - tip      : Lead
    __

    + Pencil(thickness : number)    
    + hasGrafite()       : boolean    
    + insert(lead : Lead): boolean
    + remove()           : Lead
    + writePage()        : void
    __
    + toString()         : string
}

Pencil "1" o-- "0..1" Lead : aggregates

note right of Pencil
  Uma lapiseira pode não ter grafite agregado.
  A multiplicidade 0..1 representa essa ausência.
  remove() pode não retornar um grafite.
end note
@enduml
