@startuml
skinparam defaultFontName "Source Code Pro"
skinparam dpi 150
left to right direction

class Lead {
    - thickness: number
    - hardness : string
    - size     : number
    __
    + constructor(thickness: number, hardness: string, size: number)
    + usagePerSheet(): number
    __
    + getHardness() : string
    + getSize()     : number
    + getThickness(): number
    __
    + setSize(size: number): void
    __
    + toString(): string
}

class Pencil {
    
    - thickness: number
    - tip      : Lead | null
    __

    + constructor(thickness : number)
    + hasLead()          : boolean
    + insert(lead : Lead): string | null
    + remove()           : Lead | null
    + writePage()        : string | null
    __
    + toString()         : string
}

Pencil "1" o-- "0..1" Lead : agrega

note right of Pencil
  Uma lapiseira pode não ter grafite agregado.
  A multiplicidade 0..1 representa essa ausência.
  remove() pode não retornar um grafite.
end note
@enduml
