@startuml

skinparam defaultFontName Hasklig
skinparam dpi 150

package com.qxcode {
  class Car {
    - gas     : int
    - gasMax  : int
    - km      : int
    - pass    : int
    - passMax : int
    __
    + Car()
    + toString() : string
    __
    + enter()
    + leave()
    + fuel(gas : int)
    + drive(km : int)
    __
    + getGas()  : int
    + getKm()   : int
    + getPass() : int
    +   setGas(gas : int)
    +     setKm(km : int)
    + setPass(pass : int)
  }
}
@enduml