@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

left to right direction

enum DeathCause {
    NONE
    WEAKNESS
    DIRT
}

class Pet {
    - energyMax: number
    - cleanMax : number
    - energy   : number
    - clean    : number
    - age      : number
    - alive    : boolean
    - deathCause: DeathCause
    __
    + constructor(energy: number, clean: number)
    + isAlive(): boolean
    + toString(): string
    __
    + setEnergy(value: number): void
    + setClean(value: number) : void
    + setAge(value: number)   : void
    __
    + getClean()    : number
    + getCleanMax() : number
    + getEnergy()   : number
    + getEnergyMax(): number
    + getAge()      : number
}

class Game {
    - pet: Pet
    __
    + constructor(pet: Pet)
    + toString() : string
    + isAlive() : boolean
    + isSleepy(): boolean
    __
    + play()  : boolean
    + shower(): boolean
    + sleep() : boolean
}

Game "1" o-- "1" Pet : agrega
Pet ..> DeathCause : registra

@enduml
