@startuml

skinparam defaultFontName "Source Code Pro"
skinparam dpi 150

class Garment {
  - size: string
  __
  + constructor()
  + setSize(size: string): boolean
  + getSize(): string
  + toString(): string
}

class Shell {
  __
  + main(): void
}

Shell ..> Garment : usa

@enduml
